services:
  - type: web
    name: python-etf-dashboard
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.4
